from ontology import Run, Simulation, Step


class SimRunner:

    def __init__(self): ...

    def start_sim(self, n_runs: int):
        for i in range(n_runs):
            ...

    def end_sim(self): ...
    def start_run(self): ...
    def end_run(self): ...

    def start_step(self): ...
    def end_step(self): ...
